apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  selector:
    matchLabels:
      run: apache
  template:
    metadata:
      labels:
          run: apache
    spec:
      containers:
      - name: apache-container
        image: 501545346340.dkr.ecr.us-east-1.amazonaws.com/apache_image
        ports:
        - containerPort: 80
          hostPort: 80