apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      run: elasticsearch
  template:
    metadata:
      labels:
          run: elasticsearch
    spec:
      containers:
      - name: elasticsearch-container
        image: 501545346340.dkr.ecr.us-east-1.amazonaws.com/elasticsearch
        ports:
        - containerPort: 9200
          hostPort: 9200